class GridCell {
  final String cellId; final double lat, lon; final String sensorType, sourceSceneId; final double pixelSizeM;
  final double ironIndex, claySwirIndex, quartzSilicaIndex, alterationIndex, gossanProxy, ndmi, vegetationNoise;
  final double structureScore, lineamentDensity, intersectionScore, shearOrientationDeg, nearestFaultDistanceM, dilationJogScore;
  final double slopeDeg, slopeScore, triScore, twiScore, drainageScore, accessibilityScore;
  final double clusterScore, clusterRadiusM, continuityScore, geometryScore, patternScore;
  final double noiseProbability, lateriteRisk, bariteNoiseRisk, magneticGroundRisk, uncertainty;
  final double fieldEvidenceScore; final bool visited; final String? sampleId; final int photoCount; final String assayStatus;
  const GridCell({required this.cellId,required this.lat,required this.lon,required this.sensorType,required this.sourceSceneId,required this.pixelSizeM,required this.ironIndex,required this.claySwirIndex,required this.quartzSilicaIndex,required this.alterationIndex,required this.gossanProxy,required this.ndmi,required this.vegetationNoise,required this.structureScore,required this.lineamentDensity,required this.intersectionScore,required this.shearOrientationDeg,required this.nearestFaultDistanceM,required this.dilationJogScore,required this.slopeDeg,required this.slopeScore,required this.triScore,required this.twiScore,required this.drainageScore,required this.accessibilityScore,required this.clusterScore,required this.clusterRadiusM,required this.continuityScore,required this.geometryScore,required this.patternScore,required this.noiseProbability,required this.lateriteRisk,required this.bariteNoiseRisk,required this.magneticGroundRisk,required this.uncertainty,required this.fieldEvidenceScore,required this.visited,required this.sampleId,required this.photoCount,required this.assayStatus});
  factory GridCell.fromJson(Map<String,dynamic> j){
    double d(String k,[double f=0.0])=>((j[k]??f) as num).toDouble(); String s(String k,[String f=''])=>(j[k]??f).toString();
    return GridCell(cellId:s('cell_id'),lat:d('lat'),lon:d('lon'),sensorType:s('sensor_type','fused'),sourceSceneId:s('source_scene_id'),pixelSizeM:d('pixel_size_m',30),ironIndex:d('iron_index'),claySwirIndex:d('clay_swir_index'),quartzSilicaIndex:d('quartz_silica_index'),alterationIndex:d('alteration_index'),gossanProxy:d('gossan_proxy'),ndmi:d('ndmi'),vegetationNoise:d('vegetation_noise'),structureScore:d('structure_score'),lineamentDensity:d('lineament_density'),intersectionScore:d('intersection_score'),shearOrientationDeg:d('shear_orientation_deg'),nearestFaultDistanceM:d('nearest_fault_distance_m'),dilationJogScore:d('dilation_jog_score'),slopeDeg:d('slope_deg'),slopeScore:d('slope_score'),triScore:d('tri_score'),twiScore:d('twi_score'),drainageScore:d('drainage_score'),accessibilityScore:d('accessibility_score'),clusterScore:d('cluster_score'),clusterRadiusM:d('cluster_radius_m',250),continuityScore:d('continuity_score'),geometryScore:d('geometry_score'),patternScore:d('pattern_score'),noiseProbability:d('noise_probability',0.2),lateriteRisk:d('laterite_risk',0.2),bariteNoiseRisk:d('barite_noise_risk',0.1),magneticGroundRisk:d('magnetic_ground_risk',0.5),uncertainty:d('uncertainty',0.35),fieldEvidenceScore:d('field_evidence_score'),visited:j['visited']==true,sampleId:j['sample_id']?.toString(),photoCount:(j['photo_count']??0) as int,assayStatus:s('assay_status','none'));
  }
}
