import 'package:flutter/material.dart'; import '../../domain/models/grid_cell.dart'; import '../../engines/bouh_supreme_engine.dart';
class PointAnalysisScreen extends StatefulWidget{const PointAnalysisScreen({super.key}); @override State<PointAnalysisScreen> createState()=>_S();} class _S extends State<PointAnalysisScreen>{final lat=TextEditingController(text:'20.8800'), lon=TextEditingController(text:'36.0600'), s=TextEditingController(text:'0.90'), c=TextEditingController(text:'0.82'), i=TextEditingController(text:'0.88'), q=TextEditingController(text:'0.80'), p=TextEditingController(text:'0.78'), f=TextEditingController(text:'0.30'), noise=TextEditingController(text:'0.20'), mag=TextEditingController(text:'0.76'); String out='أدخل القيم ثم اضغط تحليل.'; double v(TextEditingController c)=>double.tryParse(c.text.trim())??0.0; void analyze(){final cell=GridCell(cellId:'manual',lat:v(lat),lon:v(lon),sensorType:'manual',sourceSceneId:'manual',pixelSizeM:30,ironIndex:v(i),claySwirIndex:v(c),quartzSilicaIndex:v(q),alterationIndex:(v(c)+v(i)+v(q))/3,gossanProxy:v(i),ndmi:.5,vegetationNoise:.1,structureScore:v(s),lineamentDensity:v(s),intersectionScore:v(s),shearOrientationDeg:45,nearestFaultDistanceM:120,dilationJogScore:v(p),slopeDeg:18,slopeScore:.7,triScore:.7,twiScore:.65,drainageScore:.6,accessibilityScore:.6,clusterScore:v(p),clusterRadiusM:250,continuityScore:v(p),geometryScore:v(p),patternScore:v(p),noiseProbability:v(noise),lateriteRisk:v(noise),bariteNoiseRisk:.1,magneticGroundRisk:v(mag),uncertainty:.25,fieldEvidenceScore:v(f),visited:false,sampleId:null,photoCount:0,assayStatus:'none'); final r=BouhSupremeEngine.analyze(cell); setState(()=>out='القرار: ${r.classLabelAr}
IPI: ${r.ipiScore}
P-Score: ${r.pScore}
الثقة: ${(r.overallConfidence*100).toStringAsFixed(0)}%

${r.reasonAr}

${r.fieldActionAr}

${r.gpzStrategyAr}');} Widget input(String l,TextEditingController c)=>TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('تحليل نقطة/إحداثية',style:TextStyle(fontSize:22,color:Color(0xFFD4AF37),fontWeight:FontWeight.bold)),for(final e in {'Latitude':lat,'Longitude':lon,'Structure S':s,'Clay/SWIR C':c,'Iron I':i,'Quartz/Silica Q':q,'Pattern P':p,'Field Evidence F':f,'Noise Probability':noise,'Magnetic Ground Risk':mag}.entries) ...[input(e.key,e.value),const SizedBox(height:8)],ElevatedButton.icon(onPressed:analyze,icon:const Icon(Icons.analytics),label:const Text('تحليل')),const SizedBox(height:12),Card(color:const Color(0xFF101A14),child:Padding(padding:const EdgeInsets.all(14),child:Text(out)))]);}
